apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    
    spec:
      containers:
        - name: webapp
          image: image
          ports:
              - containerPort: 8090

---

apiVersion: v1
kind: Service
metadata:
  name: expressapp
spec:
  selector:
    app: webapp

  ports:
    - name: http
      port: 8090
      nodePort: 30080

  type: NodePort

